/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import modelos.BaseDeDatos;
import modelos.Cita;
import modelos.Paciente;
import vistas.componentes.ShowAlert;

/**
 *
 * @author claud
 */
public class CrearCita extends javax.swing.JPanel {

    /**
     * Creates new form CrearCita
     */
    BaseDeDatos database;

    public CrearCita(VentanaPrincipal ventana) {
        initComponents();

        Calendar calendario = new GregorianCalendar();
        
        int year = calendario.get(Calendar.YEAR);
        
        for(int y = year; y < year + 5; y++){
            this.fechaAño.addItem(Integer.toString(y));
        }
        
        this.fechaAño.setSelectedIndex(0);
        
        database = ventana.getDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ladoIzquierdo = new javax.swing.JPanel();
        tituloGenero = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        tituloNombrePaciente = new javax.swing.JLabel();
        tituloEdad = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        genero = new javax.swing.JComboBox<>();
        cedula = new javax.swing.JTextField();
        tituloCedula = new javax.swing.JLabel();
        tituloNumeroDeTelefono = new javax.swing.JLabel();
        numeroDeTelefono = new javax.swing.JTextField();
        tituloDireccion = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        ladoDerecho = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivoDeConsulta = new javax.swing.JTextArea();
        tituloFechaCita = new javax.swing.JLabel();
        crearCita = new javax.swing.JButton();
        tituloMotivoConsulta = new javax.swing.JLabel();
        tituloHoraDeCita = new javax.swing.JLabel();
        horaDeCita = new javax.swing.JTextField();
        tituloFechaDia = new javax.swing.JLabel();
        fechaDia = new javax.swing.JComboBox<>();
        tituloFechaMes = new javax.swing.JLabel();
        fechaMes = new javax.swing.JComboBox<>();
        fechaAño = new javax.swing.JComboBox<>();
        tituloFechaAño = new javax.swing.JLabel();

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" Dirección ");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Cita médica");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ladoIzquierdo.setBackground(new java.awt.Color(128, 221, 234));

        tituloGenero.setBackground(new java.awt.Color(0, 0, 0));
        tituloGenero.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloGenero.setForeground(new java.awt.Color(255, 255, 255));
        tituloGenero.setText(" Género ");
        tituloGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        edad.setBackground(new java.awt.Color(0, 153, 204));
        edad.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        edad.setForeground(new java.awt.Color(255, 255, 255));
        edad.setText("Ingrese su edad aquí...");
        edad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });

        tituloNombrePaciente.setBackground(new java.awt.Color(0, 0, 0));
        tituloNombrePaciente.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloNombrePaciente.setForeground(new java.awt.Color(255, 255, 255));
        tituloNombrePaciente.setText(" Nombre Completo del paciente ");
        tituloNombrePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloEdad.setBackground(new java.awt.Color(0, 0, 0));
        tituloEdad.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloEdad.setForeground(new java.awt.Color(255, 255, 255));
        tituloEdad.setText(" Edad ");
        tituloEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nombre.setBackground(new java.awt.Color(0, 153, 204));
        nombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Inserte sus nombres aquí...");
        nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        genero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        cedula.setBackground(new java.awt.Color(0, 153, 204));
        cedula.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.setText("Introduce la cedula del paciente...");
        cedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        tituloCedula.setBackground(new java.awt.Color(0, 0, 0));
        tituloCedula.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloCedula.setForeground(new java.awt.Color(255, 255, 255));
        tituloCedula.setText(" Cédula del paciente ");
        tituloCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloNumeroDeTelefono.setBackground(new java.awt.Color(0, 0, 0));
        tituloNumeroDeTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloNumeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        tituloNumeroDeTelefono.setText(" Número de télefono ");
        tituloNumeroDeTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        numeroDeTelefono.setBackground(new java.awt.Color(0, 153, 204));
        numeroDeTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        numeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        numeroDeTelefono.setText("0000-000-0000");
        numeroDeTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        numeroDeTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeTelefonoActionPerformed(evt);
            }
        });

        tituloDireccion.setBackground(new java.awt.Color(0, 0, 0));
        tituloDireccion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloDireccion.setForeground(new java.awt.Color(255, 255, 255));
        tituloDireccion.setText(" Dirección ");
        tituloDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        direccion.setBackground(new java.awt.Color(0, 153, 204));
        direccion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setText("Ingresar aquí...");
        direccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ladoIzquierdoLayout = new javax.swing.GroupLayout(ladoIzquierdo);
        ladoIzquierdo.setLayout(ladoIzquierdoLayout);
        ladoIzquierdoLayout.setHorizontalGroup(
            ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoIzquierdoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCedula)))
                    .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                        .addGroup(ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloGenero)
                            .addComponent(tituloEdad)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloDireccion)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroDeTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloNumeroDeTelefono))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ladoIzquierdoLayout.setVerticalGroup(
            ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloNombrePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tituloEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloNumeroDeTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroDeTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ladoDerecho.setBackground(new java.awt.Color(128, 221, 234));

        motivoDeConsulta.setBackground(new java.awt.Color(242, 242, 242));
        motivoDeConsulta.setColumns(20);
        motivoDeConsulta.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        motivoDeConsulta.setRows(5);
        motivoDeConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(motivoDeConsulta);

        tituloFechaCita.setBackground(new java.awt.Color(0, 0, 0));
        tituloFechaCita.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloFechaCita.setForeground(new java.awt.Color(255, 255, 255));
        tituloFechaCita.setText(" Fecha de la cita ");
        tituloFechaCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        crearCita.setBackground(new java.awt.Color(23, 156, 188));
        crearCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        crearCita.setText("Crear cita");
        crearCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCitaActionPerformed(evt);
            }
        });

        tituloMotivoConsulta.setBackground(new java.awt.Color(0, 0, 0));
        tituloMotivoConsulta.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloMotivoConsulta.setForeground(new java.awt.Color(255, 255, 255));
        tituloMotivoConsulta.setText(" Motivo de la consulta ");
        tituloMotivoConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloHoraDeCita.setBackground(new java.awt.Color(0, 0, 0));
        tituloHoraDeCita.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloHoraDeCita.setForeground(new java.awt.Color(255, 255, 255));
        tituloHoraDeCita.setText(" Hora asignada de la cita ");
        tituloHoraDeCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        horaDeCita.setBackground(new java.awt.Color(0, 153, 204));
        horaDeCita.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        horaDeCita.setForeground(new java.awt.Color(255, 255, 255));
        horaDeCita.setText("00:00");
        horaDeCita.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        horaDeCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaDeCitaActionPerformed(evt);
            }
        });

        tituloFechaDia.setBackground(new java.awt.Color(0, 0, 0));
        tituloFechaDia.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tituloFechaDia.setForeground(new java.awt.Color(255, 255, 255));
        tituloFechaDia.setText("Dia:");

        fechaDia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        fechaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaDiaActionPerformed(evt);
            }
        });

        tituloFechaMes.setBackground(new java.awt.Color(0, 0, 0));
        tituloFechaMes.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tituloFechaMes.setForeground(new java.awt.Color(255, 255, 255));
        tituloFechaMes.setText("Mes:");

        fechaMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        fechaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaMesActionPerformed(evt);
            }
        });

        fechaAño.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaAñoActionPerformed(evt);
            }
        });

        tituloFechaAño.setBackground(new java.awt.Color(0, 0, 0));
        tituloFechaAño.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tituloFechaAño.setForeground(new java.awt.Color(255, 255, 255));
        tituloFechaAño.setText("Año:");

        javax.swing.GroupLayout ladoDerechoLayout = new javax.swing.GroupLayout(ladoDerecho);
        ladoDerecho.setLayout(ladoDerechoLayout);
        ladoDerechoLayout.setHorizontalGroup(
            ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horaDeCita)
                    .addGroup(ladoDerechoLayout.createSequentialGroup()
                        .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloFechaCita)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloMotivoConsulta)
                            .addComponent(tituloHoraDeCita))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(ladoDerechoLayout.createSequentialGroup()
                .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoDerechoLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(crearCita, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ladoDerechoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloFechaDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(tituloFechaMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tituloFechaAño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaAño, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ladoDerechoLayout.setVerticalGroup(
            ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoDerechoLayout.createSequentialGroup()
                .addComponent(tituloMotivoConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloFechaCita)
                .addGap(9, 9, 9)
                .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloFechaAño)
                        .addComponent(fechaAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloFechaMes)
                        .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloFechaDia)
                        .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloHoraDeCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(horaDeCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(crearCita, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ladoIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ladoDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ladoIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ladoDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void horaDeCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaDeCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaDeCitaActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        ArrayList<Paciente> pacientes = database.getPacientes();

        for (Paciente paciente : pacientes) {
            if (paciente.getCedula().equals(this.cedula.getText())) {
                this.nombre.setText(paciente.getNombre());
                this.edad.setText(Integer.toString(paciente.getEdad()));

                if (paciente.getGenero().equals("Masculino")) {
                    this.genero.setSelectedIndex(0);
                } else {
                    this.genero.setSelectedIndex(1);
                }

                this.numeroDeTelefono.setText(paciente.getTelefono());
                this.direccion.setText(paciente.getDireccion());
                
                return;
            }
        }
        
        ShowAlert alerta = new ShowAlert("Error", "No se encontro el paciente", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_cedulaActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void numeroDeTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDeTelefonoActionPerformed

    private void crearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCitaActionPerformed
        // TODO add your handling code here:

        if (cedula.getText().equals("Introduce la cedula del paciente...") || cedula.getText().isEmpty() || cedula.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte una cedula", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nombre.getText().equals("Inserte sus nombres aquí...") || nombre.getText().isEmpty() || nombre.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte un nombre", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (edad.getText().equals("Ingrese su edad aquí...") || edad.getText().isEmpty() || edad.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte una edad", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (numeroDeTelefono.getText().equals("0000-000-0000") || numeroDeTelefono.getText().isEmpty() || numeroDeTelefono.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte un numero de telefono", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (direccion.getText().equals("Ingresar aquí...") || direccion.getText().isEmpty() || direccion.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte una direccion", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (motivoDeConsulta.getText().isEmpty() || motivoDeConsulta.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte un Motivo de consulta", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ArrayList<Paciente> pacientes = database.getPacientes();

        boolean exist = false;
        Paciente pacien = new Paciente();

        for (Paciente paciente : pacientes) {
            if (paciente.getCedula().equals(cedula.getText())) {
                exist = true;
                pacien = paciente;
                break;
            }
        }

        String fechaCita = (String)this.fechaAño.getSelectedItem() + "-" + (String)this.fechaMes.getSelectedItem() + "-" + (String)this.fechaDia.getSelectedItem();
        
        if (exist) {
            Paciente paciente = pacien;

            Cita cita = new Cita(database.getCitas().size() + 1, paciente.getId(), fechaCita, horaDeCita.getText(), this.motivoDeConsulta.getText());
            database.escribirNuevaCita(cita);
            
            int[] temp = new int[paciente.getHistorial().getIdCitasPrevias().length + 1];
            
            for(int i = 0; i < temp.length; i++){
                if(i != temp.length - 1){
                    temp[i] = paciente.getHistorial().getIdCitasPrevias()[i];
                } else {
                    temp[i] = cita.getId();
                }
            }
            
            paciente.getHistorial().setIdCitasPrevias(temp);
            
            database.modificarPaciente(paciente);
        } else {
            Paciente paciente = new Paciente(database.getPacientes().size() + 1, nombre.getText(), cedula.getText(), direccion.getText(), numeroDeTelefono.getText(), Integer.parseInt(edad.getText()), (String) genero.getSelectedItem(), database.getCitas().size() + 1);
            database.escribirNuevoPaciente(paciente);

            Cita cita = new Cita(database.getCitas().size() + 1, paciente.getId(), fechaCita, horaDeCita.getText(), this.motivoDeConsulta.getText());
            database.escribirNuevaCita(cita);
        }
        
        this.nombre.setText("Inserte sus nombres aquí...");
        this.cedula.setText("Introduce la cedula del paciente...");
        this.direccion.setText("Ingresar aquí...");
        this.horaDeCita.setText("00:00");
        this.numeroDeTelefono.setText("0000-000-0000");
        this.motivoDeConsulta.setText("");
        this.edad.setText("Ingrese su edad aquí...");
        
        ShowAlert alerta = new ShowAlert("Finalizado", "Se ha creado con exito la cita", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_crearCitaActionPerformed

    private void fechaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaDiaActionPerformed

    private void fechaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaMesActionPerformed

    private void fechaAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaAñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JTextField cedula;
    private javax.swing.JButton crearCita;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField edad;
    private javax.swing.JComboBox<String> fechaAño;
    private javax.swing.JComboBox<String> fechaDia;
    private javax.swing.JComboBox<String> fechaMes;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JTextField horaDeCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel ladoDerecho;
    private javax.swing.JPanel ladoIzquierdo;
    private javax.swing.JTextArea motivoDeConsulta;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroDeTelefono;
    private javax.swing.JLabel tituloCedula;
    private javax.swing.JLabel tituloDireccion;
    private javax.swing.JLabel tituloEdad;
    private javax.swing.JLabel tituloFechaAño;
    private javax.swing.JLabel tituloFechaCita;
    private javax.swing.JLabel tituloFechaDia;
    private javax.swing.JLabel tituloFechaMes;
    private javax.swing.JLabel tituloGenero;
    private javax.swing.JLabel tituloHoraDeCita;
    private javax.swing.JLabel tituloMotivoConsulta;
    private javax.swing.JLabel tituloNombrePaciente;
    private javax.swing.JLabel tituloNumeroDeTelefono;
    // End of variables declaration//GEN-END:variables
}
