/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.BaseDeDatos;
import modelos.Paciente;
import vistas.componentes.ShowAlert;

/**
 *
 * @author yorman
 */
public class ModificarHistorial extends javax.swing.JPanel {

    BaseDeDatos database;

    /**
     * Creates new form ModificarHistorial
     */
    public ModificarHistorial(VentanaPrincipal ventana) {
        initComponents();

        this.database = ventana.getDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ladoIzquierdo = new javax.swing.JPanel();
        tituloGenero = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        tituloNombrePaciente = new javax.swing.JLabel();
        tituloEdad = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        genero = new javax.swing.JComboBox<>();
        cedula = new javax.swing.JTextField();
        tituloCedula = new javax.swing.JLabel();
        tituloNumeroDeTelefono = new javax.swing.JLabel();
        numeroDeTelefono = new javax.swing.JTextField();
        tituloDireccion = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        ladoDerecho = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alergias = new javax.swing.JTextArea();
        tituloFechaCita = new javax.swing.JLabel();
        modificarHistorial = new javax.swing.JButton();
        tituloMotivoConsulta = new javax.swing.JLabel();
        tituloHoraDeCita = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        antecedentesMedicosGenerales = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        antecedentesOftalmologicosPrevios = new javax.swing.JTextArea();
        tituloHoraDeCita1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tratamientosOftalmologicosPrevios = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Modificar Historial de Paciente");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ladoIzquierdo.setBackground(new java.awt.Color(126, 206, 255));

        tituloGenero.setBackground(new java.awt.Color(0, 0, 0));
        tituloGenero.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloGenero.setForeground(new java.awt.Color(255, 255, 255));
        tituloGenero.setText(" Género ");
        tituloGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        edad.setEditable(false);
        edad.setBackground(new java.awt.Color(0, 153, 204));
        edad.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        edad.setForeground(new java.awt.Color(255, 255, 255));
        edad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });

        tituloNombrePaciente.setBackground(new java.awt.Color(0, 0, 0));
        tituloNombrePaciente.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloNombrePaciente.setForeground(new java.awt.Color(255, 255, 255));
        tituloNombrePaciente.setText(" Nombre Completo del paciente ");
        tituloNombrePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloEdad.setBackground(new java.awt.Color(0, 0, 0));
        tituloEdad.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloEdad.setForeground(new java.awt.Color(255, 255, 255));
        tituloEdad.setText(" Edad ");
        tituloEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(0, 153, 204));
        nombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        genero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        cedula.setBackground(new java.awt.Color(0, 153, 204));
        cedula.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.setText("Introduce la cedula del paciente...");
        cedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        tituloCedula.setBackground(new java.awt.Color(0, 0, 0));
        tituloCedula.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloCedula.setForeground(new java.awt.Color(255, 255, 255));
        tituloCedula.setText(" Cédula del paciente ");
        tituloCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloNumeroDeTelefono.setBackground(new java.awt.Color(0, 0, 0));
        tituloNumeroDeTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloNumeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        tituloNumeroDeTelefono.setText(" Número de télefono ");
        tituloNumeroDeTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        numeroDeTelefono.setEditable(false);
        numeroDeTelefono.setBackground(new java.awt.Color(0, 153, 204));
        numeroDeTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        numeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        numeroDeTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        numeroDeTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeTelefonoActionPerformed(evt);
            }
        });

        tituloDireccion.setBackground(new java.awt.Color(0, 0, 0));
        tituloDireccion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloDireccion.setForeground(new java.awt.Color(255, 255, 255));
        tituloDireccion.setText(" Dirección ");
        tituloDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        direccion.setEditable(false);
        direccion.setBackground(new java.awt.Color(0, 153, 204));
        direccion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ladoIzquierdoLayout = new javax.swing.GroupLayout(ladoIzquierdo);
        ladoIzquierdo.setLayout(ladoIzquierdoLayout);
        ladoIzquierdoLayout.setHorizontalGroup(
            ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoIzquierdoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCedula)))
                    .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                        .addGroup(ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloGenero)
                            .addComponent(tituloEdad)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloDireccion)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroDeTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloNumeroDeTelefono))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ladoIzquierdoLayout.setVerticalGroup(
            ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloNombrePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tituloEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloNumeroDeTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroDeTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ladoDerecho.setBackground(new java.awt.Color(126, 206, 255));

        alergias.setBackground(new java.awt.Color(232, 227, 227));
        alergias.setColumns(20);
        alergias.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        alergias.setRows(5);
        alergias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(alergias);

        tituloFechaCita.setBackground(new java.awt.Color(0, 0, 0));
        tituloFechaCita.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloFechaCita.setForeground(new java.awt.Color(255, 255, 255));
        tituloFechaCita.setText("Antecedentes Medicos Generales");
        tituloFechaCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        modificarHistorial.setBackground(new java.awt.Color(23, 156, 188));
        modificarHistorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modificarHistorial.setText("Modificar Historial");
        modificarHistorial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarHistorialActionPerformed(evt);
            }
        });

        tituloMotivoConsulta.setBackground(new java.awt.Color(0, 0, 0));
        tituloMotivoConsulta.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloMotivoConsulta.setForeground(new java.awt.Color(255, 255, 255));
        tituloMotivoConsulta.setText("Alergias");
        tituloMotivoConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloHoraDeCita.setBackground(new java.awt.Color(0, 0, 0));
        tituloHoraDeCita.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloHoraDeCita.setForeground(new java.awt.Color(255, 255, 255));
        tituloHoraDeCita.setText("Antecedentes Oftalmologicos Previos");
        tituloHoraDeCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        antecedentesMedicosGenerales.setBackground(new java.awt.Color(232, 227, 227));
        antecedentesMedicosGenerales.setColumns(20);
        antecedentesMedicosGenerales.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        antecedentesMedicosGenerales.setRows(5);
        antecedentesMedicosGenerales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(antecedentesMedicosGenerales);

        antecedentesOftalmologicosPrevios.setBackground(new java.awt.Color(232, 227, 227));
        antecedentesOftalmologicosPrevios.setColumns(20);
        antecedentesOftalmologicosPrevios.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        antecedentesOftalmologicosPrevios.setRows(5);
        antecedentesOftalmologicosPrevios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(antecedentesOftalmologicosPrevios);

        tituloHoraDeCita1.setBackground(new java.awt.Color(0, 0, 0));
        tituloHoraDeCita1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloHoraDeCita1.setForeground(new java.awt.Color(255, 255, 255));
        tituloHoraDeCita1.setText("Tratamientos Oftalmologicos Previos");
        tituloHoraDeCita1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tratamientosOftalmologicosPrevios.setBackground(new java.awt.Color(232, 227, 227));
        tratamientosOftalmologicosPrevios.setColumns(20);
        tratamientosOftalmologicosPrevios.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tratamientosOftalmologicosPrevios.setRows(5);
        tratamientosOftalmologicosPrevios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(tratamientosOftalmologicosPrevios);

        javax.swing.GroupLayout ladoDerechoLayout = new javax.swing.GroupLayout(ladoDerecho);
        ladoDerecho.setLayout(ladoDerechoLayout);
        ladoDerechoLayout.setHorizontalGroup(
            ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoDerechoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(ladoDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoDerechoLayout.createSequentialGroup()
                        .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ladoDerechoLayout.createSequentialGroup()
                        .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloFechaCita)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloMotivoConsulta)
                            .addComponent(tituloHoraDeCita)
                            .addComponent(tituloHoraDeCita1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        ladoDerechoLayout.setVerticalGroup(
            ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoDerechoLayout.createSequentialGroup()
                .addComponent(tituloMotivoConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloFechaCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tituloHoraDeCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloHoraDeCita1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(modificarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ladoIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ladoDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ladoIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ladoDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        ArrayList<Paciente> pacientes = database.getPacientes();

        for (Paciente paciente : pacientes) {
            if (paciente.getCedula().equals(this.cedula.getText())) {
                this.nombre.setText(paciente.getNombre());
                this.edad.setText(Integer.toString(paciente.getEdad()));

                if (paciente.getGenero().equals("Masculino")) {
                    this.genero.setSelectedIndex(0);
                } else {
                    this.genero.setSelectedIndex(1);
                }

                this.numeroDeTelefono.setText(paciente.getTelefono());
                this.direccion.setText(paciente.getDireccion());

                this.alergias.setText(paciente.getHistorial().getAlergias());
                this.antecedentesMedicosGenerales.setText(paciente.getHistorial().getAntecedentesMedicosGenerales());
                this.antecedentesOftalmologicosPrevios.setText(paciente.getHistorial().getAntecedentesOftalmologicos());
                this.tratamientosOftalmologicosPrevios.setText(paciente.getHistorial().getTratamientosOftalmologicosPrevios());

                return;
            }
        }

        ShowAlert alerta = new ShowAlert("Error", "No se encontro el paciente", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_cedulaActionPerformed

    private void numeroDeTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDeTelefonoActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void modificarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarHistorialActionPerformed
        // TODO add your handling code here:

        if (cedula.getText().equals("Introduce la cedula del paciente...") || cedula.getText().isEmpty() || cedula.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte una cedula", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nombre.getText().equals("Inserte sus nombres aquí...") || nombre.getText().isEmpty() || nombre.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte un nombre", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (edad.getText().equals("Ingrese su edad aquí...") || edad.getText().isEmpty() || edad.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte una edad", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (numeroDeTelefono.getText().equals("0000-000-0000") || numeroDeTelefono.getText().isEmpty() || numeroDeTelefono.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte un numero de telefono", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (direccion.getText().equals("Ingresar aquí...") || direccion.getText().isEmpty() || direccion.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte una direccion", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ArrayList<Paciente> pacientes = database.getPacientes();

        Paciente paciente = null;

        for (Paciente temp : pacientes) {
            if (temp.getCedula().equals(cedula.getText())) {
                paciente = temp;
                break;
            }
        }

        if (paciente == null) {
            ShowAlert alerta = new ShowAlert("Error", "No se encontro el paciente", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        paciente.getHistorial().setAlergias(this.alergias.getText());
        paciente.getHistorial().setAntecedentesMedicosGenerales(this.antecedentesMedicosGenerales.getText());
        paciente.getHistorial().setAntecedentesOftalmologicos(this.antecedentesOftalmologicosPrevios.getText());
        paciente.getHistorial().setTratamientosOftalmologicosPrevios(this.tratamientosOftalmologicosPrevios.getText());
        
        this.database.modificarPaciente(paciente);
        
        ShowAlert alerta = new ShowAlert("Exito", "Se modifico el historial con exito", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_modificarHistorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alergias;
    private javax.swing.JTextArea antecedentesMedicosGenerales;
    private javax.swing.JTextArea antecedentesOftalmologicosPrevios;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField edad;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel ladoDerecho;
    private javax.swing.JPanel ladoIzquierdo;
    private javax.swing.JButton modificarHistorial;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroDeTelefono;
    private javax.swing.JLabel tituloCedula;
    private javax.swing.JLabel tituloDireccion;
    private javax.swing.JLabel tituloEdad;
    private javax.swing.JLabel tituloFechaCita;
    private javax.swing.JLabel tituloGenero;
    private javax.swing.JLabel tituloHoraDeCita;
    private javax.swing.JLabel tituloHoraDeCita1;
    private javax.swing.JLabel tituloMotivoConsulta;
    private javax.swing.JLabel tituloNombrePaciente;
    private javax.swing.JLabel tituloNumeroDeTelefono;
    private javax.swing.JTextArea tratamientosOftalmologicosPrevios;
    // End of variables declaration//GEN-END:variables
}
