/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import modelos.BaseDeDatos;
import modelos.Cita;
import modelos.Factura;
import modelos.Paciente;
import vistas.componentes.CitasCarta;
import vistas.componentes.FacturaCarta;

/**
 *
 * @author yorman
 */
public class MostrarHistorial extends javax.swing.JPanel {

    BaseDeDatos database;

    /**
     * Creates new form MostrarHistorial
     */
    public MostrarHistorial(VentanaPrincipal ventana) {
        initComponents();

        this.database = ventana.getDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        containerInformacionPaciente = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        tituloNombre = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        separadorNombre = new javax.swing.JSeparator();
        panelDireccion = new javax.swing.JPanel();
        tituloDireccion = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        separadorDireccion = new javax.swing.JSeparator();
        panelCedula = new javax.swing.JPanel();
        tituloCedula = new javax.swing.JLabel();
        cedulaTextField = new javax.swing.JTextField();
        panelEdad = new javax.swing.JPanel();
        tituloEdad = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        separadorEdad = new javax.swing.JSeparator();
        panelTelefono = new javax.swing.JPanel();
        tituloTelefono = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        separadorTelefono = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        containerDatosHistorial = new javax.swing.JPanel();
        alergias = new javax.swing.JLabel();
        antecedentesMedicosGenerales = new javax.swing.JLabel();
        antecedentesOftalmologicos = new javax.swing.JLabel();
        tratamientosOftalmologicosPrevios = new javax.swing.JLabel();
        citasPrevias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        containerGrid = new javax.swing.JPanel();

        jScrollPane2.setViewportView(jEditorPane1);

        containerInformacionPaciente.setBackground(new java.awt.Color(204, 239, 255));

        panelNombre.setBackground(new java.awt.Color(204, 239, 255));

        tituloNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloNombre.setText("Nombre:");

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombre.setText(" ");
        labelNombre.setToolTipText("");

        separadorNombre.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelNombreLayout = new javax.swing.GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloNombre)
                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(separadorNombre))
                .addGap(0, 0, 0))
        );
        panelNombreLayout.setVerticalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre)
                .addGap(2, 2, 2)
                .addComponent(separadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelDireccion.setBackground(new java.awt.Color(204, 239, 255));

        tituloDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloDireccion.setText("Direccion:");

        labelDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDireccion.setText(" ");

        separadorDireccion.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelDireccionLayout = new javax.swing.GroupLayout(panelDireccion);
        panelDireccion.setLayout(panelDireccionLayout);
        panelDireccionLayout.setHorizontalGroup(
            panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(separadorDireccion)
                    .addComponent(tituloDireccion)
                    .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        panelDireccionLayout.setVerticalGroup(
            panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDireccion)
                .addGap(2, 2, 2)
                .addComponent(separadorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelCedula.setBackground(new java.awt.Color(204, 239, 255));

        tituloCedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloCedula.setText("Cedula:");

        cedulaTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCedulaLayout = new javax.swing.GroupLayout(panelCedula);
        panelCedula.setLayout(panelCedulaLayout);
        panelCedulaLayout.setHorizontalGroup(
            panelCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCedulaLayout.createSequentialGroup()
                .addGroup(panelCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCedula)
                    .addComponent(cedulaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCedulaLayout.setVerticalGroup(
            panelCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCedulaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cedulaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelEdad.setBackground(new java.awt.Color(204, 239, 255));

        tituloEdad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloEdad.setText("Edad:");

        labelEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEdad.setText(" ");
        labelEdad.setToolTipText("");

        separadorEdad.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelEdadLayout = new javax.swing.GroupLayout(panelEdad);
        panelEdad.setLayout(panelEdadLayout);
        panelEdadLayout.setHorizontalGroup(
            panelEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdadLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separadorEdad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEdadLayout.setVerticalGroup(
            panelEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdadLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEdad)
                .addGap(2, 2, 2)
                .addComponent(separadorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelTelefono.setBackground(new java.awt.Color(204, 239, 255));

        tituloTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloTelefono.setText("Telefono:");

        labelTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTelefono.setText(" ");
        labelTelefono.setToolTipText("");

        separadorTelefono.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelTelefonoLayout = new javax.swing.GroupLayout(panelTelefono);
        panelTelefono.setLayout(panelTelefonoLayout);
        panelTelefonoLayout.setHorizontalGroup(
            panelTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelefonoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTelefono)
                    .addComponent(labelTelefono)
                    .addComponent(separadorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTelefonoLayout.setVerticalGroup(
            panelTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelefonoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTelefono)
                .addGap(2, 2, 2)
                .addComponent(separadorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout containerInformacionPacienteLayout = new javax.swing.GroupLayout(containerInformacionPaciente);
        containerInformacionPaciente.setLayout(containerInformacionPacienteLayout);
        containerInformacionPacienteLayout.setHorizontalGroup(
            containerInformacionPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInformacionPacienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(containerInformacionPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(containerInformacionPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerInformacionPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        containerInformacionPacienteLayout.setVerticalGroup(
            containerInformacionPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInformacionPacienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(containerInformacionPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerInformacionPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        containerDatosHistorial.setBackground(new java.awt.Color(51, 184, 255));
        containerDatosHistorial.setPreferredSize(new java.awt.Dimension(900, 68));

        alergias.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        alergias.setText("<html><body style=\"margin: 5px 10px 2px 10px; font-weight: bold\">Alergias: <span style=\"font-weight: normal\">Elija un paciente</span></body></html>");
        alergias.setToolTipText("");

        antecedentesMedicosGenerales.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        antecedentesMedicosGenerales.setText("<html><body style=\"margin: 2px 10px 2px 10px; font-weight: bold\">Antecedentes Medicos Generales: <span style=\"font-weight: normal\">Elija un paciente</span></body></html>");

        antecedentesOftalmologicos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        antecedentesOftalmologicos.setText("<html><body style=\"margin: 2px 10px 2px 10px; font-weight: bold\">Antecedentes Oftalmologicos: <span style=\"font-weight: normal\">Elija un paciente</span></body></html>");

        tratamientosOftalmologicosPrevios.setBackground(new java.awt.Color(204, 204, 255));
        tratamientosOftalmologicosPrevios.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tratamientosOftalmologicosPrevios.setText("<html><body style=\"margin: 2px 10px 2px 10px; font-weight: bold\">Tratamientos Oftalmologicos Previos: <span style=\"font-weight: normal\">Elija un paciente</span></body></html>");

        citasPrevias.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        citasPrevias.setText("Citas Previas:");

        javax.swing.GroupLayout containerDatosHistorialLayout = new javax.swing.GroupLayout(containerDatosHistorial);
        containerDatosHistorial.setLayout(containerDatosHistorialLayout);
        containerDatosHistorialLayout.setHorizontalGroup(
            containerDatosHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerDatosHistorialLayout.createSequentialGroup()
                .addGroup(containerDatosHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerDatosHistorialLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(citasPrevias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(alergias, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tratamientosOftalmologicosPrevios, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antecedentesOftalmologicos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antecedentesMedicosGenerales, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, 0))
        );
        containerDatosHistorialLayout.setVerticalGroup(
            containerDatosHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerDatosHistorialLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(alergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(antecedentesMedicosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(antecedentesOftalmologicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tratamientosOftalmologicosPrevios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(citasPrevias))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(902, 333));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        containerGrid.setBackground(new java.awt.Color(153, 233, 255));
        containerGrid.setPreferredSize(new java.awt.Dimension(100, 100));
        containerGrid.setLayout(new java.awt.GridLayout(2, 2, 30, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(containerDatosHistorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(containerDatosHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerInformacionPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(containerInformacionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTextFieldActionPerformed
        this.containerGrid.removeAll();
        ArrayList<Paciente> pacientes = database.getPacientes();

        for (Paciente paciente : pacientes) {
            if (paciente.getCedula().equals(this.cedulaTextField.getText())) {
                this.cedulaTextField.setFocusable(false);
                this.cedulaTextField.setFocusable(true);

                this.labelNombre.setText(paciente.getNombre());
                this.labelDireccion.setText(paciente.getDireccion());
                this.labelEdad.setText(Integer.toString(paciente.getEdad()));
                this.labelTelefono.setText(paciente.getTelefono());

                this.alergias.setText("<html><body style='margin: 5px 10px 2px 10px'><span style='font-weight: bold'>Alergias:</span> <span>" + paciente.getHistorial().getAlergias() + "</span></body></html>");
                this.antecedentesMedicosGenerales.setText("<html><body style='margin: 2px 10px 2px 10px'><span style='font-weight: bold'>Antecedentes Medicos Generales:</span> <span>" + paciente.getHistorial().getAntecedentesMedicosGenerales() + "</span></body></html>");
                this.antecedentesOftalmologicos.setText("<html><body style='margin: 2px 10px 2px 10px'><span style='font-weight: bold'>Antecedentes Oftalmologicos:</span> <span>" + paciente.getHistorial().getAntecedentesOftalmologicos() + "</span></body></html>");
                this.tratamientosOftalmologicosPrevios.setText("<html><body style='margin: 2px 10px 5px 10px'><span style='font-weight: bold'>Tratamientos Oftalmologicos Previos:</span> <span>" + paciente.getHistorial().getTratamientosOftalmologicosPrevios() + "</span></body></html>");

                ArrayList<Cita> citas = new ArrayList<>();

                for (Cita cita : database.getCitas()) {
                    if (cita.getIdPaciente() == paciente.getId()) {
                        citas.add(cita);
                    }
                }

                ArrayList<Factura> facturas = database.getFacturas();
                for (Cita cita : citas) {
                    Factura factura = new Factura();

                    for (Factura fac : facturas) {
                        if (fac.getId() == cita.getIdFactura()) {
                            factura = fac;
                            break;
                        }
                    }
                    containerGrid.add(new CitasCarta(cita, factura));
                }

                int temp = (citas.size() % 2 != 0) ? citas.size() + 1 : citas.size();

                double cantidadDeFilas = temp / 2;

                containerGrid.setLayout(new java.awt.GridLayout((int) cantidadDeFilas, 2, 30, 30));
                containerGrid.repaint();
                containerGrid.revalidate();

                return;
            }
        }
    }//GEN-LAST:event_cedulaTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alergias;
    private javax.swing.JLabel antecedentesMedicosGenerales;
    private javax.swing.JLabel antecedentesOftalmologicos;
    private javax.swing.JTextField cedulaTextField;
    private javax.swing.JLabel citasPrevias;
    private javax.swing.JPanel containerDatosHistorial;
    private javax.swing.JPanel containerGrid;
    private javax.swing.JPanel containerInformacionPaciente;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JPanel panelCedula;
    private javax.swing.JPanel panelDireccion;
    private javax.swing.JPanel panelEdad;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelTelefono;
    private javax.swing.JSeparator separadorDireccion;
    private javax.swing.JSeparator separadorEdad;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorTelefono;
    private javax.swing.JLabel tituloCedula;
    private javax.swing.JLabel tituloDireccion;
    private javax.swing.JLabel tituloEdad;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloTelefono;
    private javax.swing.JLabel tratamientosOftalmologicosPrevios;
    // End of variables declaration//GEN-END:variables
}
