/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import modelos.BaseDeDatos;
import modelos.Cita;
import modelos.Factura;
import modelos.Paciente;
import modelos.Pago;
import vistas.componentes.ShowAlert;

/**
 *
 * @author claud
 */
public class CrearInformeMedico extends javax.swing.JPanel {

    BaseDeDatos database;

    /**
     * Creates new form CrearInformeMedico
     */
    public CrearInformeMedico(VentanaPrincipal ventana) {
        initComponents();

        this.database = ventana.getDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ladoIzquierdo = new javax.swing.JPanel();
        tituloGenero = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        tituloNombrePaciente = new javax.swing.JLabel();
        tituloEdad = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        genero = new javax.swing.JComboBox<>();
        cedula = new javax.swing.JTextField();
        tituloCedula = new javax.swing.JLabel();
        tituloNumeroDeTelefono = new javax.swing.JLabel();
        numeroDeTelefono = new javax.swing.JTextField();
        tituloDireccion = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        tituloNombrePaciente1 = new javax.swing.JLabel();
        identificadorDeCita = new javax.swing.JComboBox<>();
        ladoDerecho = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnostico = new javax.swing.JTextArea();
        crearFactura = new javax.swing.JButton();
        tituloDiagnostico = new javax.swing.JLabel();
        tituloTratamiento = new javax.swing.JLabel();
        tituloMedicamentos = new javax.swing.JLabel();
        tituloExamenOcular = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        examenOcular = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tratamiento = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        medicamentos = new javax.swing.JTextArea();
        tituloRazon = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        razon = new javax.swing.JTextArea();

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tratamiento");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar Informe Medico");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(3, 0));

        ladoIzquierdo.setBackground(new java.awt.Color(0, 153, 153));

        tituloGenero.setBackground(new java.awt.Color(0, 0, 0));
        tituloGenero.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloGenero.setForeground(new java.awt.Color(255, 255, 255));
        tituloGenero.setText(" Género ");
        tituloGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        edad.setEditable(false);
        edad.setBackground(new java.awt.Color(0, 153, 153));
        edad.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        edad.setForeground(new java.awt.Color(255, 255, 255));
        edad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });

        tituloNombrePaciente.setBackground(new java.awt.Color(0, 0, 0));
        tituloNombrePaciente.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloNombrePaciente.setForeground(new java.awt.Color(255, 255, 255));
        tituloNombrePaciente.setText(" Nombre Completo del paciente ");
        tituloNombrePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloEdad.setBackground(new java.awt.Color(0, 0, 0));
        tituloEdad.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloEdad.setForeground(new java.awt.Color(255, 255, 255));
        tituloEdad.setText(" Edad ");
        tituloEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(0, 153, 153));
        nombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        genero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        cedula.setBackground(new java.awt.Color(0, 153, 153));
        cedula.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.setText("Introduce la cedula del paciente...");
        cedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        tituloCedula.setBackground(new java.awt.Color(0, 0, 0));
        tituloCedula.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloCedula.setForeground(new java.awt.Color(255, 255, 255));
        tituloCedula.setText(" Cédula del paciente ");
        tituloCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloNumeroDeTelefono.setBackground(new java.awt.Color(0, 0, 0));
        tituloNumeroDeTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloNumeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        tituloNumeroDeTelefono.setText(" Número de télefono ");
        tituloNumeroDeTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        numeroDeTelefono.setEditable(false);
        numeroDeTelefono.setBackground(new java.awt.Color(0, 153, 153));
        numeroDeTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        numeroDeTelefono.setForeground(new java.awt.Color(255, 255, 255));
        numeroDeTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        tituloDireccion.setBackground(new java.awt.Color(0, 0, 0));
        tituloDireccion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloDireccion.setForeground(new java.awt.Color(255, 255, 255));
        tituloDireccion.setText(" Dirección ");
        tituloDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        direccion.setEditable(false);
        direccion.setBackground(new java.awt.Color(0, 153, 153));
        direccion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        tituloNombrePaciente1.setBackground(new java.awt.Color(0, 0, 0));
        tituloNombrePaciente1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloNombrePaciente1.setForeground(new java.awt.Color(255, 255, 255));
        tituloNombrePaciente1.setText("Identificador de Cita");
        tituloNombrePaciente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        identificadorDeCita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        identificadorDeCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificadorDeCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ladoIzquierdoLayout = new javax.swing.GroupLayout(ladoIzquierdo);
        ladoIzquierdo.setLayout(ladoIzquierdoLayout);
        ladoIzquierdoLayout.setHorizontalGroup(
            ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloNombrePaciente)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloGenero)
                    .addComponent(tituloEdad)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloDireccion)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroDeTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloNumeroDeTelefono)
                    .addComponent(tituloCedula)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificadorDeCita, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloNombrePaciente1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ladoIzquierdoLayout.setVerticalGroup(
            ladoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloNombrePaciente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(identificadorDeCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloNombrePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tituloEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloNumeroDeTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroDeTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ladoDerecho.setBackground(new java.awt.Color(0, 153, 153));

        diagnostico.setColumns(20);
        diagnostico.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        diagnostico.setRows(5);
        diagnostico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(diagnostico);

        crearFactura.setBackground(new java.awt.Color(23, 156, 188));
        crearFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        crearFactura.setText("Modificar Informe Medico");
        crearFactura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFacturaActionPerformed(evt);
            }
        });

        tituloDiagnostico.setBackground(new java.awt.Color(0, 0, 0));
        tituloDiagnostico.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloDiagnostico.setForeground(new java.awt.Color(255, 255, 255));
        tituloDiagnostico.setText("Diagnostico");
        tituloDiagnostico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloTratamiento.setBackground(new java.awt.Color(0, 0, 0));
        tituloTratamiento.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        tituloTratamiento.setText("Tratamiento");
        tituloTratamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloMedicamentos.setBackground(new java.awt.Color(0, 0, 0));
        tituloMedicamentos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        tituloMedicamentos.setText("Medicamentos");
        tituloMedicamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tituloExamenOcular.setBackground(new java.awt.Color(0, 0, 0));
        tituloExamenOcular.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloExamenOcular.setForeground(new java.awt.Color(255, 255, 255));
        tituloExamenOcular.setText("Examen Ocular");
        tituloExamenOcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        examenOcular.setColumns(20);
        examenOcular.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        examenOcular.setRows(5);
        examenOcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(examenOcular);

        tratamiento.setColumns(20);
        tratamiento.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tratamiento.setRows(5);
        tratamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(tratamiento);

        medicamentos.setColumns(20);
        medicamentos.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        medicamentos.setRows(5);
        medicamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(medicamentos);

        tituloRazon.setBackground(new java.awt.Color(0, 0, 0));
        tituloRazon.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        tituloRazon.setForeground(new java.awt.Color(255, 255, 255));
        tituloRazon.setText("Razon");
        tituloRazon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        razon.setEditable(false);
        razon.setColumns(20);
        razon.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        razon.setRows(5);
        razon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(razon);

        javax.swing.GroupLayout ladoDerechoLayout = new javax.swing.GroupLayout(ladoDerecho);
        ladoDerecho.setLayout(ladoDerechoLayout);
        ladoDerechoLayout.setHorizontalGroup(
            ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoDerechoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(crearFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoDerechoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tituloRazon)
                .addGap(382, 382, 382))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoDerechoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tituloMedicamentos)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloTratamiento)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloDiagnostico)
                            .addComponent(tituloExamenOcular)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ladoDerechoLayout.setVerticalGroup(
            ladoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoDerechoLayout.createSequentialGroup()
                .addComponent(tituloRazon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(tituloExamenOcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloDiagnostico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloTratamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloMedicamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ladoIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ladoDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ladoIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ladoDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        ArrayList<Paciente> pacientes = database.getPacientes();

        for (Paciente paciente : pacientes) {
            if (paciente.getCedula().equals(this.cedula.getText())) {
                this.nombre.setText(paciente.getNombre());
                this.edad.setText(Integer.toString(paciente.getEdad()));

                if (paciente.getGenero().equals("Masculino")) {
                    this.genero.setSelectedIndex(0);
                } else {
                    this.genero.setSelectedIndex(1);
                }

                this.numeroDeTelefono.setText(paciente.getTelefono());
                this.direccion.setText(paciente.getDireccion());

                ArrayList<Cita> citas = this.database.getCitas();

                ArrayList<Cita> citasSinFactura = new ArrayList<>();

                this.identificadorDeCita.removeAllItems();

                for (Cita cita : citas) {
                    if (cita.getIdPaciente() == paciente.getId() && !cita.isCompletada()) {
                        citasSinFactura.add(cita);
                    }
                }
                
                if(citasSinFactura.isEmpty()){
                    ShowAlert alerta = new ShowAlert("Error", "El paciente seleccionado no tiene citas pendientes", JOptionPane.ERROR_MESSAGE);
                    this.razon.setText("");
                    return;
                }
                
                for(Cita cita: citasSinFactura){
                    this.identificadorDeCita.addItem(Integer.toString(cita.getId()));
                }

                if (citasSinFactura.size() > 0) {
                    this.razon.setText(citasSinFactura.get(0).getRazon());
                }

                return;
            }
        }

        ShowAlert alerta = new ShowAlert("Error", "No se encontro el paciente", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_cedulaActionPerformed

    private void crearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFacturaActionPerformed
        // TODO add your handling code here:

        if (cedula.getText().equals("Introduce la cedula del paciente...") || cedula.getText().isEmpty() || cedula.getText().isBlank()) {
            ShowAlert alerta = new ShowAlert("Error", "Inserte una cedula", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ArrayList<Paciente> pacientes = database.getPacientes();

        Paciente pacien = new Paciente();

        Paciente paciente = null;

        for (Paciente temp : pacientes) {
            if (temp.getCedula().equals(cedula.getText())) {
                paciente = temp;
                break;
            }
        }

        if (paciente == null) {
            ShowAlert alerta = new ShowAlert("Error", "No se encontro el paciente", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int identificadorCita = Integer.parseInt(this.identificadorDeCita.getItemAt(this.identificadorDeCita.getSelectedIndex()));

            ArrayList<Cita> citas = this.database.getCitas();

            Cita cita = null;
            for (Cita c : citas) {
                if (c.getId() == identificadorCita && c.getIdPaciente() == paciente.getId()) {
                    cita = c;
                }
            }

            if (cita == null) {
                ShowAlert alerta = new ShowAlert("Error", "No se ha encontrado la cita", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (cita.isCompletada()) {
                ShowAlert alerta = new ShowAlert("Error", "Esta cita medica ya esta completada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            cita.getInformeDeCita().setDignostico(this.diagnostico.getText());
            cita.getInformeDeCita().setExamenOcular(this.examenOcular.getText());
            cita.getInformeDeCita().setMedicamentos(this.medicamentos.getText());
            cita.getInformeDeCita().setTratamiento(this.tratamiento.getText());

            this.database.modificarCita(cita);
            ShowAlert showAlert = new ShowAlert("Finalizado", "Se ha creado el informe", JOptionPane.PLAIN_MESSAGE);

            this.cedula.setText("Introduce la cedula del paciente...");
            this.nombre.setText("");
            this.edad.setText("");
            this.genero.setSelectedIndex(0);
            this.direccion.setText("");
            this.numeroDeTelefono.setText("");

            this.identificadorDeCita.removeAllItems();
            this.examenOcular.setText("");
            this.diagnostico.setText("");
            this.tratamiento.setText("");
            this.medicamentos.setText("");
            this.razon.setText("");
        } catch (Exception err) {
            ShowAlert alerta = new ShowAlert("Error", "Introdusca un numero de cita valido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearFacturaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void identificadorDeCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificadorDeCitaActionPerformed
        // TODO add your handling code here:

        try {
            int idCita = Integer.parseInt(this.identificadorDeCita.getItemAt(this.identificadorDeCita.getSelectedIndex()));

            ArrayList<Cita> citas = this.database.getCitas();

            for (Cita cita : citas) {
                if (cita.getId() == idCita) {
                    this.razon.setText(cita.getRazon());
                    break;
                }
            }
        } catch(Exception err){
            this.razon.setText("");
            if(cedula.getText().equals("Introduce la cedula del paciente...")){
                ShowAlert alerta = new ShowAlert("Error", "El id de la cita no es valido", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_identificadorDeCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedula;
    private javax.swing.JButton crearFactura;
    private javax.swing.JTextArea diagnostico;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField edad;
    private javax.swing.JTextArea examenOcular;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JComboBox<String> identificadorDeCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel ladoDerecho;
    private javax.swing.JPanel ladoIzquierdo;
    private javax.swing.JTextArea medicamentos;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroDeTelefono;
    private javax.swing.JTextArea razon;
    private javax.swing.JLabel tituloCedula;
    private javax.swing.JLabel tituloDiagnostico;
    private javax.swing.JLabel tituloDireccion;
    private javax.swing.JLabel tituloEdad;
    private javax.swing.JLabel tituloExamenOcular;
    private javax.swing.JLabel tituloGenero;
    private javax.swing.JLabel tituloMedicamentos;
    private javax.swing.JLabel tituloNombrePaciente;
    private javax.swing.JLabel tituloNombrePaciente1;
    private javax.swing.JLabel tituloNumeroDeTelefono;
    private javax.swing.JLabel tituloRazon;
    private javax.swing.JLabel tituloTratamiento;
    private javax.swing.JTextArea tratamiento;
    // End of variables declaration//GEN-END:variables
}
