/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Component;

/**
 *
 * @author yorman
 */
public class MenuSecretaria extends javax.swing.JPanel {

    /**
     * Creates new form MenuEnfermera
     */
    public MenuSecretaria() {
        initComponents();

        this.panelPaciente.remove(this.citaPacienteLabel);
        this.panelPaciente.remove(this.historialPacienteLabel);
        this.panelPaciente.remove(this.facturaPacienteLabel);

        this.panelPaciente.repaint();
        this.panelPaciente.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPaciente = new javax.swing.JPanel();
        labelPaciente = new javax.swing.JLabel();
        citaPacienteLabel = new javax.swing.JLabel();
        historialPacienteLabel = new javax.swing.JLabel();
        facturaPacienteLabel = new javax.swing.JLabel();
        panelConsultorio = new javax.swing.JPanel();
        labelConsultorio = new javax.swing.JLabel();
        panelInventario = new javax.swing.JPanel();
        labelInventario = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelPaciente.setLayout(new javax.swing.BoxLayout(panelPaciente, javax.swing.BoxLayout.Y_AXIS));

        labelPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPaciente.setText("Paciente");
        labelPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPacienteMousePressed(evt);
            }
        });
        panelPaciente.add(labelPaciente);

        citaPacienteLabel.setText("Cita");
        panelPaciente.add(citaPacienteLabel);

        historialPacienteLabel.setText("Historial");
        historialPacienteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPaciente.add(historialPacienteLabel);

        facturaPacienteLabel.setText("Factura");
        panelPaciente.add(facturaPacienteLabel);

        add(panelPaciente);

        panelConsultorio.setLayout(new javax.swing.BoxLayout(panelConsultorio, javax.swing.BoxLayout.Y_AXIS));

        labelConsultorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelConsultorio.setText("Consultorio");
        panelConsultorio.add(labelConsultorio);

        add(panelConsultorio);

        panelInventario.setLayout(new javax.swing.BoxLayout(panelInventario, javax.swing.BoxLayout.Y_AXIS));

        labelInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelInventario.setText("Inventario");
        panelInventario.add(labelInventario);

        add(panelInventario);
    }// </editor-fold>//GEN-END:initComponents

    private void labelPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPacienteMousePressed
        Component componentes[] = this.panelPaciente.getComponents();

        if (componentes.length != 1) {
            this.panelPaciente.remove(this.citaPacienteLabel);
            this.panelPaciente.remove(this.historialPacienteLabel);
            this.panelPaciente.remove(this.facturaPacienteLabel);

            this.panelPaciente.repaint();
            this.panelPaciente.revalidate();
        } else {
            this.panelPaciente.add(this.citaPacienteLabel);
            this.panelPaciente.add(this.historialPacienteLabel);
            this.panelPaciente.add(this.facturaPacienteLabel);

            this.panelPaciente.repaint();
            this.panelPaciente.revalidate();
        }
    }//GEN-LAST:event_labelPacienteMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel citaPacienteLabel;
    private javax.swing.JLabel facturaPacienteLabel;
    private javax.swing.JLabel historialPacienteLabel;
    private javax.swing.JLabel labelConsultorio;
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JPanel panelConsultorio;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelPaciente;
    // End of variables declaration//GEN-END:variables
}
