/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.componentes;

import modelos.Factura;
import modelos.Pago;

/**
 *
 * @author yorman
 */
public class FacturaCarta extends javax.swing.JPanel {

    /**
     * Creates new form FacturaCarta
     * @param factura
     */
    public FacturaCarta(Factura factura) {
        initComponents();

        numeroDeFactura.setText("<html><body style='margin: 5px 10px 2px 10px'><span style='font-weight: bold'>Numero de Factura:</span> <span>" + factura.getId() + "</span></body></html>");
  
        Pago pago = factura.getPago();

        if (factura.isPagado()) {
            String metodoDePago = "";

            switch (pago.getMetodoDePago()) {
                case Pago.MetodosDePago.PAGO_MOVIL:
                    metodoDePago = "Pago Movil";
                    break;
                case Pago.MetodosDePago.EFECTIVO:
                    metodoDePago = "Efectivo";
                    break;
                default:
                    metodoDePago = "Efectivo";
                    break;
            }

            this.metodoDePago.setText("<html><body style='margin: 2px 10px'><span style='font-weight: bold'>Metodo de Pago:</span> <span>" + metodoDePago + "</span></body></html>");
        } else {
            this.metodoDePago.setText("<html><body style='margin: 2px 10px'><span style='font-weight: bold'>Metodo de Pago:</span> <span>Sin Pagar</span></body></html>");
        }
        
        examenes.setText("<html><body style='margin: 2px 10px; font-weigth: bold'>Examenes:</body></html>");
        
        String listaExamenesTexto = "";
        
        String[] arrExamenes = factura.getExamenes().split("\n");
        
        for(int i = 0; i < arrExamenes.length; i++){
            listaExamenesTexto += "<li>" + arrExamenes[i] + "</li>";
        }
        
        listaExamenes.setText("<html><body><ul>" + listaExamenesTexto + "</ul></body></html>");
        
        monto.setText("<html><body style='margin: 2px 10px 5px 10px'><span style='font-weight: bold'>Monto:</span> <span>" + factura.getPago().getMonto() + "</span></body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroDeFactura = new javax.swing.JLabel();
        metodoDePago = new javax.swing.JLabel();
        examenes = new javax.swing.JLabel();
        listaExamenes = new javax.swing.JLabel();
        monto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        numeroDeFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroDeFactura.setText("Numero de Factura: 1");
        add(numeroDeFactura);

        metodoDePago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        metodoDePago.setText("Metodo de Pago: Pago Movil");
        add(metodoDePago);

        examenes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        examenes.setText("Examenes:");
        add(examenes);

        listaExamenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(listaExamenes);

        monto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monto.setText("Monto: 200 Bs");
        add(monto);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel examenes;
    private javax.swing.JLabel listaExamenes;
    private javax.swing.JLabel metodoDePago;
    private javax.swing.JLabel monto;
    private javax.swing.JLabel numeroDeFactura;
    // End of variables declaration//GEN-END:variables
}
