/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.componentes;

import modelos.MaterialMedico;

/**
 *
 * @author yorman
 */
public class MaterialesMedicosCarta extends javax.swing.JPanel {

    /**
     * Creates new form MaterialesMedicosCarta
     */
    public MaterialesMedicosCarta(MaterialMedico material) {
        initComponents();
        
        this.codigoDeMaterial.setText("<html><body style='margin: 2px 10px 2px 10px'><span style='font-weight: bold'>Codigo del Material:</span> <span>" + material.getCodigo() + "</span></body></html>");
        this.nombre.setText("<html><body style='margin: 2px 10px 2px 10px'><span style='font-weight: bold'>Nombre del Material:</span> <span>" + material.getNombreMaterial() + "</span></body></html>");
        this.descripcion.setText(material.getDescripcion());
        this.cantidad.setText("<html><body style='margin: 2px 10px 2px 10px'><span style='font-weight: bold'>Cantidad:</span> <span>" + material.getCantidad() + "</span></body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoDeMaterial = new javax.swing.JLabel();
        numeroDeFactura = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        tituloDescripcion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        listaExamenes = new javax.swing.JLabel();

        codigoDeMaterial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoDeMaterial.setText("Codigo de Material: A1");

        numeroDeFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.setText("Nombre Material: Bisturi");

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantidad.setText("Cantidad: 12");

        tituloDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloDescripcion.setText("Materiales:");

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        listaExamenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(codigoDeMaterial)
            .addComponent(numeroDeFactura)
            .addComponent(nombre)
            .addComponent(cantidad)
            .addComponent(tituloDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(codigoDeMaterial)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroDeFactura)
                    .addComponent(nombre))
                .addComponent(cantidad)
                .addGap(0, 0, 0)
                .addComponent(tituloDescripcion)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel codigoDeMaterial;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listaExamenes;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel numeroDeFactura;
    private javax.swing.JLabel tituloDescripcion;
    // End of variables declaration//GEN-END:variables
}
